### ISSUE TITLE
Diagnosing shapefile update issues

### ISSUE THREAD

**Issue by danrademacher** [oceanplanning/oceanplanning.org#1]
From @nwehner via email:

> I’m trying to add 2 new regions to the map (the Northeast and the Mid-Atlantic) which are both correctly projected to WGS 84 out of the box. But, whenever I add the new layers to the map, every other layer disappears. I’m hoping you all can help me figure out what’s going on. I pretty darn sure I have the environment all setup on my mac correctly, and I think I followed the directions properly.

I pulled the latest changes and confirmed that the layers are not loading on the map. Also noticed that the layer picker is not loading;
![image](https://cloud.githubusercontent.com/assets/1423200/8015290/2a75169e-0b8c-11e5-856e-c8e0ca3f4814.png)

I suspect the topojson error in the console is a symptom of the problem and the rendering of the page is just stalling out. That error message is opaque to me, however, since it's on a minified js file that's one long line.

In reviewing the [data prep steps](https://github.com/oceanplanning/oceanplanning.org#data-preparation-geographical-files), I found that the new layers (one is [here](https://github.com/oceanplanning/oceanplanning.org/tree/master/data/nroc)) don't seem to have been rendered out of the shapefiles into the GeoJSON, [here](https://github.com/oceanplanning/oceanplanning.org/tree/master/assets/geojson), and so they are not present in the [topojson](https://github.com/oceanplanning/oceanplanning.org/blob/master/assets/geojson-low/planning_areas.topojson) that actually loads on the map. 

It looks like @nwehner added the GeoJSON files manually, in [this commit](https://github.com/oceanplanning/oceanplanning.org/commit/7882ef79d703b6a0be90bef839d5dcb92ca440e90), but when I load the topojson in QGIS, those elements are not present. 

Still trying to figure out what's what. @nwehner if there's anything else you can append here in terms of what happened when you processed the files, that would be helpful in diagnosing the issues.

**Comment by nwehner** [comment]
I reverted a few recent commits, and the layers are showing up properly again. The odd thing is, after reverting those commits (for the codebase, not the GitHub page) there were no changes to the GitHub page after Gulping. Which must mean there's some code then that's pulled from oceanplanning.org but not from oceanplanning.github.io like it should be, right?

**Comment by danrademacher** [comment]
We're going to need some reinforcements on this from @sconnelley -- he should have some time later this week to take a look.

**Comment by sconnelley** [comment]
@nwehner -- 
Can give you me a little more info on what wasn't pulled over during the Gulp process: GeoJSON files, JS files ?

About the new layers not showing up on the map, did you update the [Makefile](https://github.com/oceanplanning/oceanplanning.org/blob/master/Makefile) 

If not, you need to add something like this to the Makefile: (@almccon set this up so ping him if this doesn't work) 

```
$(JSONDIR)/nroc_data_development_area.geojson: $(DATADIR)/nroc/nroc_data_development_area.shp
    ogr2ogr -f "GeoJSON" -t_srs "EPSG:4326" $@ $<
```

And then:

```
geojson: jsondir \
$(JSONDIR)/ma_coastalzone.geojson \
....
$(JSONDIR)/nroc_data_development_area.geojson \
```

```
topojson:
    $(TOPOJSON) -q 60000 --simplify-proportion 0.7 -p -o $(JSONDIR)/planning_areas.topojson \
$(JSONDIR)/ma_coastalzone.geojson \
....
$(JSONDIR)/nroc_data_development_area.geojson \
```

```
topojson-low:
    $(TOPOJSON) -q 1e5 -s 0.0000001 -p -o $(JSONLOWDIR)/planning_areas.topojson \
$(JSONDIR)/ma_coastalzone.geojson \
....
$(JSONDIR)/nroc_data_development_area.geojson \
```

**Comment by nwehner** [comment]
Hey guys - sorry I’m going to be out of the office until the 21st. I’ll definitely get back to you when I return!

**Comment by nwehner** [comment]
I found the sticking point from before. I added the Makefile changes from @almccon (now committed) and ran `make topojson` which gives the following error message:

> ENOENT, no such file or directory 'assets/geojson/nroc_data_development_area.geojson'

That's why I tried to manually create the geojson file myself earlier. Shouldn't the `make topojson` command create that file?

**Comment by nwehner** [comment]
I just tried manually creating the geojsons again, and then running `make topojson` so it could just start running with the geojsons as they're already present. That seemed to run smoothly....until I gulped and committed the changes from the github submodule - which broke all the layering again. I'll leave everything as-is (i.e. broken from my latest commits) now so you can see what I mean.

**Comment by almccon** [comment]
It looks like the `marco_data_development_area.shp` is in a projection that `ogr2ogr` can't parse. Here's the error I get when I try to run `make assets/geojson/marco_data_development_area.geojson`

```
$ make assets/geojson/marco_data_development_area.geojson
ogr2ogr -f "GeoJSON" -t_srs "EPSG:4326" assets/geojson/marco_data_development_area.geojson data/marco/marco_data_development_area.shp
ERROR 6: No translation for Mercator_Auxiliary_Sphere to PROJ.4 format is known.
Failed to create coordinate transformation between the
following coordinate systems.  This may be because they
are not transformable, or because projection services
(PROJ.4 DLL/.so) could not be loaded.
Source:
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",
    GEOGCS["GCS_WGS_1984",
        DATUM["WGS_1984",
            SPHEROID["WGS_84",6378137.0,298.257223563]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Mercator_Auxiliary_Sphere"],
    PARAMETER["False_Easting",0.0],
    PARAMETER["False_Northing",0.0],
    PARAMETER["Central_Meridian",0.0],
    PARAMETER["Standard_Parallel_1",0.0],
    PARAMETER["Auxiliary_Sphere_Type",0.0],
    UNIT["Meter",1.0]]
Target:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
ERROR 1: Terminating translation prematurely after failed
translation of layer marco_data_development_area (use -skipfailures to skip errors)

make: *** [assets/geojson/marco_data_development_area.geojson] Error 1
```

It's the WGS_1984_Web_Mercator_Auxiliary_Sphere projection that's the problem, which seems to be an ESRI-specific way of describing Web Mercator.

@nwehner, the geojson you created manually seems like it's still in Web Mercator. Looking inside, I see the coordinates are all like `-8465843.67159999907, 4385004.624200001358986`, which appear to be x/y in meters, not lat/lon. The `topojson` step in the Makefile doesn't know how to deal with these, because it's expecting lat/lon.

Here's the fix I came up with: I've changed the `marco_data_development_area.geojson` line in the Makefile so that it specifies the source projection (using `-s_srs "EPSG:3857"`) to be something that `ogr2ogr` can understand (but which is still the same as the WGS_1984_Web_Mercator_Auxiliary_Sphere, just a different name).

`ogr2ogr -f "GeoJSON" -t_srs "EPSG:4326" -s_srs "EPSG:3857" assets/geojson/marco_data_development_area.geojson data/marco/marco_data_development_area.shp`

Added the fixed files here: eac0c2fd1a5718a0b7f827ada9e3a204181601a9

Looks good on the live site: 
![screen shot 2015-06-23 at 23 jun 8 06 42](https://cloud.githubusercontent.com/assets/1212178/8322010/8dcade26-19e3-11e5-9e64-216bf64a5111.png)

@nwehner can you confirm that this looks right?

**Comment by nwehner** [comment]
Looks like that's all working fine! Thank you! I'll make sure to contact the MARCO people as I'm sure the planning regions shouldn't overlap - must be the projection they're using. 

Is the `make assets/geojson/foo.geojson` standard procedure? Or if the projections are cooperative, shouldn't the `make topojson` command take care of both processing the geojson and topojson files? From the documentation, it seems the latter.

**Comment by almccon** [comment]
Hi @nwehner. The overlapping planning areas is probably not due to projections... the areas line up too perfectly everywhere else.

And no,  `make assets/geojson/foo.geojson` should not be standard procedure. `make topojson` should call that correctly behind the scenes. But, if there are failures that are happening, it's helpful to manually run the intermediate steps (like `make foo.geojson`) to see if any error messages are surfacing that we can do something about. That's what was the case in this situation.
